config/routes.rb
Rails.application.routes.draw do
  resources :homeworks
  devise_for :users
  root 'home#index'
  get 'home/about'

end

app/models/homework.rb
class Homework
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  field :speciality, type: String
  field :course_name, type: String
  field :question, type: String
  field :homework_status, type: String,default: 'Pending'
  field :submission_deadline, type: Date
  field :payment_status, type: String,default: 'Unpaid'

  validates :question,:course_name,presence: true

  belongs_to :user
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""
  field :admin, type: Mongoid::Boolean, default: false

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  # field :sign_in_count,      type: Integer, default: 0
  # field :current_sign_in_at, type: Time
  # field :last_sign_in_at,    type: Time
  # field :current_sign_in_ip, type: String
  # field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  validates :email, presence: true, uniqueness: true
  validates :encrypted_password, presence: true
  has_many :homeworks




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def index
  end

  def about
  end
end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  before_action :set_homework, only: %i[ show edit update destroy ]

  # GET /homeworks or /homeworks.json
  def index
    @homeworks = Homework.all
  end

  # GET /homeworks/1 or /homeworks/1.json
  def show
  end

  # GET /homeworks/new
  def new
    @homework = Homework.new
  end

  # GET /homeworks/1/edit
  def edit
  end

  # POST /homeworks or /homeworks.json
  def create
    @homework = Homework.new(homework_params)
    @homework.user = current_user

    respond_to do |format|
      if @homework.save
        format.html { redirect_to @homework, notice: "Homework was successfully created." }
        format.json { render :show, status: :created, location: @homework }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homeworks/1 or /homeworks/1.json
  def update
    respond_to do |format|
      if @homework.update(homework_params)
        format.html { redirect_to @homework, notice: "Homework was successfully updated." }
        format.json { render :show, status: :ok, location: @homework }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homeworks/1 or /homeworks/1.json
  def destroy
    @homework.destroy
    respond_to do |format|
      format.html { redirect_to homeworks_url, notice: "Homework was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_homework
      @homework = Homework.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def homework_params
      params.require(:homework).permit(:speciality, :course_name, :question, :homework_status, :submission_deadline, :payment_status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/views/home/about.html.erb
<h1 class="text-center">About us</h1>

app/views/home/index.html.erb
<h1 class="text-center">WAJBK</h1>

<img src="app/assets/images/books.png" class="img-fluid" alt="book image">

app/views/homeworks/_form.html.erb
<%= form_with(model: homework, local: true) do |form| %>
  <% if homework.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(homework.errors.count, "error") %> prohibited this homework from being saved:</h2>

      <ul>
      <% homework.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="input-group mb-4">
    <%= form.text_field :speciality,
                        id: :homework_speciality,
                        class: "form-control",
                        placeholder:"Speciality" %>
    <%= form.text_field :course_name,
                        id: :homework_course_name,
                        class: "form-control",
                        placeholder:"Course Name" %>
  </div>


  <div class="field form-group">
    <%= form.text_area :question,
                       id: :homework_question,
                       class:"form-control mb-4 p-5 text-center",
                       placeholder: "Write Your HomeWork" %>
  </div>


  <div class="field form-group">
    <%= form.text_field :homework_status,
                        id: :homework_homework_status,
                        placeholder: "Homework Status",
                        class: "form-control text-center border border-dark mb-4",
                        readonly: true %>
  </div>

  <div class="field">
    <%= form.text_field :payment_status,
                        id: :homework_payment_status,
                        placeholder: "Payment Status",
                        class: "form-control text-center border border-dark mb-4",
                        readonly: true %>
  </div>

  <div class="text-center mb-4">
  <div class="field form-group text-light bg-dark">
    <%= form.label :submission_deadline %>
    <%= form.date_select :submission_deadline,class: "form-control", id: :homework_submission_deadline %>
  </div>
  </div>

  <div class="actions text-center">
    <%= form.submit "Add Homework",class: "btn btn-dark" %>
  </div>
<% end %>

app/views/homeworks/edit.html.erb
<h1 class="text-center">Editing Homework</h1>

<%= render 'form', homework: @homework %>

<%= link_to 'Back', homeworks_path %>

app/views/homeworks/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Homeworks</h1>
<% @count= 0  %>
<table class="table table-hover table-dark ">
  <thead>
    <tr>
      <th scope="col">Number</th>
      <th scope="col">Speciality</th>
      <th scope="col">Course name</th>
      <th scope="col">Question</th>
      <th scope="col">Submission deadline</th>
      <th scope="col">Homework status</th>
      <th scope="col">Payment status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homeworks.each do |homework| %>
    <% @count = @count+1 %>
      <tr>
        <td scope="row"><%= @count %></td>
        <td><%= homework.speciality %></td>
        <td><%= homework.course_name %></td>
        <td><%= homework.question %></td>
        <td><%= homework.submission_deadline %></td>
        <td><%= homework.homework_status %></td>
        <td><%= homework.payment_status %></td>
        <td><%= link_to 'Show', homework %></td>
        <td><%= link_to 'Edit', edit_homework_path(homework) %></td>
        <td><%= link_to 'Destroy', homework, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Homework', new_homework_path %>

app/views/homeworks/new.html.erb
<h1 class="text-center">New Homework</h1>

<%= render 'form', homework: @homework %>

app/views/homeworks/show.html.erb
<p id="notice"><%= notice %></p>
<table class="table table-hover table-dark ">

  <thead>
  <tr>
    <th scope="col"><strong>Speciality:</strong></th>
    <th scope="col"><strong>Course name:</strong></th>
    <th scope="col"><strong>Question:</strong></th>
    <th scope="col"><strong>Submission deadline:</strong></th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td><%= @homework.speciality %></td>
    <td><%= @homework.course_name %></td>
    <td><%= @homework.question %></td>
    <td><%= @homework.submission_deadline %></td>
  </tr>
  </tbody>
</table>

<%= link_to 'Back', homeworks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wajbk</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl"
          crossorigin="anonymous">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flash_notice' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash_notice.html.erb
<% if notice or alert %>
  <div class="alert alert-dark" role="alert">
    <%= notice %>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <div class="container-fluid">

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">

        <% if current_user %>

          <li class="nav-item">
            <%= link_to 'Home', root_path, class: "nav-link active" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Add Homework', new_homework_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'My Homeworks', homeworks_path, class: "nav-link" %>
          </li>


          <li class="nav-item">
            <%= link_to 'About', home_about_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>

        <% else %>

          <li class="nav-item">
          </li>

          <li class="nav-item">
            <%= link_to 'About', home_about_path, class: "nav-link" %>
          </li>

        <% end %>

      </ul>
      <!--      <form class="d-flex">-->
      <!--        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">-->
      <!--        <button class="btn btn-outline-success" type="submit">Search</button>-->
      <!--      </form>-->
    </div>
  </div>
</nav>